<a href="https://colab.research.google.com/github/siddhesh1503/Machine-Learning/blob/main/GridSearchCV.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop('species',axis = 1)
y = df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [8]:
from sklearn.neighbors import KNeighborsClassifier

In [9]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [10]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [12]:
model_knn.score(X_test,y_test)

1.0

In [18]:
from sklearn.svm import SVC

In [19]:
model_svm = SVC(C = 30, kernel='rbf', gamma='auto')

In [20]:
model_svm.fit(X_train,y_train)

SVC(C=30, gamma='auto')

In [21]:
model_svm.score(X_test,y_test)

0.98

In [22]:
#Now lets see use the grid search CV

In [23]:
from sklearn.model_selection import GridSearchCV

In [31]:
classifier = GridSearchCV((model_svm), {
    'C':[1,10,20,30],
    'kernel':['rbf','linear']
},cv = 5,return_train_score = False)

In [32]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [34]:
classifier.cv_results_

{'mean_fit_time': array([0.00569367, 0.00458732, 0.0073842 , 0.00514336, 0.00245857,
        0.00231428, 0.00251317, 0.00210061]),
 'std_fit_time': array([1.39224076e-03, 9.51336171e-04, 3.96492566e-03, 2.18566130e-03,
        5.02093746e-04, 2.57141015e-04, 2.16363514e-04, 4.13290475e-05]),
 'mean_score_time': array([0.00450902, 0.00289307, 0.00529747, 0.003508  , 0.00193763,
        0.00202551, 0.00191321, 0.00162244]),
 'std_score_time': array([1.62548357e-03, 1.01366944e-04, 2.88405400e-03, 8.83633737e-04,
        4.32936629e-04, 4.18690955e-04, 1.78238043e-04, 3.76683247e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.95, 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.9 , 0.9 , 0.8 , 0.85, 0.8 , 0.85, 0.8 , 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.95, 0.95, 1.  , 0.95, 0.95, 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.94, 0.95, 0.93, 0.93, 0.92, 0.93, 0.93, 0.94]),
 'std_test_score': array([0.03741657, 0.04472136, 0.07483315, 0.0509902 , 0.0678233 ,
        0.0509902 , 0.07483315, 0.05830952]),
 'rank_test_score': array([2, 1, 4, 6, 8, 6, 4, 3], dtype=int32)}

In [35]:
results = pd.DataFrame(classifier.cv_results_)

In [36]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005694,0.001392,0.004509,0.001625,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,2
1,0.004587,0.000951,0.002893,0.000101,1,linear,"{'C': 1, 'kernel': 'linear'}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
2,0.007384,0.003965,0.005297,0.002884,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
3,0.005143,0.002186,0.003508,0.000884,10,linear,"{'C': 10, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,6
4,0.002459,0.000502,0.001938,0.000433,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,0.95,0.92,0.067823,8
5,0.002314,0.000257,0.002026,0.000419,20,linear,"{'C': 20, 'kernel': 'linear'}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,6
6,0.002513,0.000216,0.001913,0.000178,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.95,0.80,0.9,1.00,1.00,0.93,0.074833,4
7,0.002101,0.000041,0.001622,0.000038,30,linear,"{'C': 30, 'kernel': 'linear'}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,3

In [37]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.94
1        1       linear             0.95
2       10          rbf             0.93
3       10       linear             0.93
4       20          rbf             0.92
5       20       linear             0.93
6       30          rbf             0.93
7       30       linear             0.94

In [38]:
from sklearn.model_selection import RandomizedSearchCV

In [39]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

In [40]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(C=30, gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [41]:
RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [42]:
results = pd.DataFrame(classifier_r.cv_results_)

In [43]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004630,0.001571,0.002799,0.000331,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004082,0.000242,0.003545,0.000665,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,2
2,0.003435,0.000365,0.002523,0.000381,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,3
3,0.006682,0.006056,0.002819,0.000203,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4

In [44]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333
2       20       linear         0.966667
3       30       linear         0.960000